apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagebroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagebroker
  template:
    metadata:
      labels:
        app: messagebroker
    spec:
      restartPolicy: Always
      containers:
        - name: messagebroker
          image: rabbitmq:management
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.2"
            limits:
              memory: "256Mi"
              cpu: "0.5"
      hostname: sportybuddies-mq
---
apiVersion: v1
kind: Service
metadata:
  name: messagebroker-service
spec:
  selector:
    app: messagebroker
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
