apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityservice
  template:
    metadata:
      labels:
        app: identityservice
    spec:
      restartPolicy: Always
      containers:
        - name: identityservice
          image: identityservice:latest
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Database
              value: Server=mssql-service;Database=IdentityDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True;
            - name: MessageBroker__Host
              value: amqp://messagebroker-service:5672
            - name: MessageBroker__Password
              value: guest
            - name: MessageBroker__UserName
              value: guest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.2"
            limits:
              memory: "256Mi"
              cpu: "0.5"
          volumeMounts:
            - mountPath: /app/keys
              name: identityservice-claim0
      volumes:
        - name: identityservice-claim0
          persistentVolumeClaim:
            claimName: identityservice-claim0
---
apiVersion: v1
kind: Service
metadata:
  name: identityservice-service
spec:
  type: NodePort
  selector:
    app: identityservice
  ports:
    - protocol: TCP
      port: 6065
      targetPort: 8080
      nodePort: 31065