apiVersion : apps/v1
kind: Deployment
metadata:
  name: sportapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportapi
  template:
    metadata:
      labels:
        app: sportapi 
    spec:
      containers:
        - name: sportapi 
          image: sportybuddiesacr.azurecr.io/sportapi
          ports:
          - containerPort: 8080