apiVersion: apps/v1
kind: Deployment
metadata:
  name: profilemanagementapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profilemanagementapi
  template:
    metadata:
      labels:
        app: profilemanagementapi
    spec:
      restartPolicy: Always
      containers:
        - name: profilemanagementapi
          image: tbaran2001/profilemanagementapi:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Database
              value: Server=mssql-service;Database=ProfileDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True;
            - name: ConnectionStrings__Redis
              value: distributedcache:6379
            - name: FeatureManagement__Matching
              value: "false"
            - name: IdentityServiceUrl
              value: http://identityservice-service:6065
            - name: Jwt__Audience
              value: profilemanagement-api
            - name: Jwt__Authority
              value: http://identityservice-service:6065
            - name: Jwt__MetadataAddress
              value: http://identityservice-service:6065/.well-known/openid-configuration
            - name: Jwt__RequireHttpsMetadata
              value: "false"
            - name: MessageBroker__Host
              value: amqp://messagebroker-service:5672
            - name: MessageBroker__Password
              value: guest
            - name: MessageBroker__UserName
              value: guest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.2"
            limits:
              memory: "256Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: profilemanagementapi-service
spec:
  type: NodePort
  selector:
    app: profilemanagementapi
  ports:
    - protocol: TCP
      port: 6003
      targetPort: 8080
      nodePort: 31003