apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sportapi
  template:
    metadata:
      labels:
        app: sportapi
    spec:
      containers:
        - name: sportapi
          image: tbaran2001/sportapi:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Database
              valueFrom:
                configMapKeyRef:
                  name: mssql-configmap
                  key: connection_string
            - name: Jwt__Audience
              value: sport-api
            - name: Jwt__Authority
              value: http://identityservice:8080
            - name: Jwt__MetadataAddress
              value: http://identityservice:8080/.well-known/openid-configuration
            - name: Jwt__RequireHttpsMetadata
              value: "false"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.2"
            limits:
              memory: "256Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: sportapi-service
spec:
  type: NodePort
  selector:
    app: sportapi
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 8080
      nodePort: 31000