// <auto-generated />
using System;
using Buddies.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buddies.API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250209212307_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buddies.API.Buddies.Models.Buddy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MatchedProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OppositeBuddyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Buddies");
                });

            modelBuilder.Entity("Buddies.API.Buddies.Models.Buddy", b =>
                {
                    b.OwnsOne("Buddies.API.Buddies.ValueObjects.CreatedAt", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("BuddyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedAt");

                            b1.HasKey("BuddyId");

                            b1.ToTable("Buddies");

                            b1.WithOwner()
                                .HasForeignKey("BuddyId");
                        });

                    b.Navigation("CreatedAt");
                });
#pragma warning restore 612, 618
        }
    }
}
