// <auto-generated />
using System;
using Buddies.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buddies.API.Data.Migrations
{
    [DbContext(typeof(BuddyDbContext))]
    partial class BuddyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buddies.API.Buddies.Models.Buddy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatchedProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OppositeBuddyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Buddies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6410e3d-3f8e-4216-a982-daca6402309b"),
                            CreatedOnUtc = new DateTime(2025, 1, 8, 14, 9, 33, 290, DateTimeKind.Utc).AddTicks(1962),
                            MatchedProfileId = new Guid("13ba1cf4-831b-4d88-9545-471b352a0744"),
                            OppositeBuddyId = new Guid("2680f1f5-cadb-4011-8a44-a75e06c49ae9"),
                            ProfileId = new Guid("087e44eb-9044-4ebb-b2e1-0e67d12a7395")
                        },
                        new
                        {
                            Id = new Guid("2680f1f5-cadb-4011-8a44-a75e06c49ae9"),
                            CreatedOnUtc = new DateTime(2025, 1, 8, 14, 9, 33, 290, DateTimeKind.Utc).AddTicks(1962),
                            MatchedProfileId = new Guid("087e44eb-9044-4ebb-b2e1-0e67d12a7395"),
                            OppositeBuddyId = new Guid("d6410e3d-3f8e-4216-a982-daca6402309b"),
                            ProfileId = new Guid("13ba1cf4-831b-4d88-9545-471b352a0744")
                        },
                        new
                        {
                            Id = new Guid("f980fdcf-99ad-47e5-8b71-e515c7990fa1"),
                            CreatedOnUtc = new DateTime(2025, 1, 8, 14, 9, 33, 290, DateTimeKind.Utc).AddTicks(1985),
                            MatchedProfileId = new Guid("0efcc60c-59b2-4678-ac00-46d24cf870ea"),
                            OppositeBuddyId = new Guid("3f6d154b-832d-4666-862c-97b5e47ef18c"),
                            ProfileId = new Guid("087e44eb-9044-4ebb-b2e1-0e67d12a7395")
                        },
                        new
                        {
                            Id = new Guid("3f6d154b-832d-4666-862c-97b5e47ef18c"),
                            CreatedOnUtc = new DateTime(2025, 1, 8, 14, 9, 33, 290, DateTimeKind.Utc).AddTicks(1985),
                            MatchedProfileId = new Guid("087e44eb-9044-4ebb-b2e1-0e67d12a7395"),
                            OppositeBuddyId = new Guid("f980fdcf-99ad-47e5-8b71-e515c7990fa1"),
                            ProfileId = new Guid("0efcc60c-59b2-4678-ac00-46d24cf870ea")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
