version: '3.4'

services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server

  distributedcache:
    image: redis

  messagebroker:
    image: rabbitmq:management

  sport.api:
    image: ${DOCKER_REGISTRY-}sportapi
    build:
      context: .
      dockerfile: Services/Sport/Sport.API/Dockerfile

  buddies.api:
    image: ${DOCKER_REGISTRY-}buddiesapi
    build:
      context: .
      dockerfile: Services/Buddies/src/Buddies.API/Dockerfile

  matching.api:
    image: ${DOCKER_REGISTRY-}matchingapi
    build:
      context: .
      dockerfile: Services/Matching/src/Matching.API/Dockerfile

  profilemanagement.api:
    image: ${DOCKER_REGISTRY-}profilemanagementapi
    build:
      context: .
      dockerfile: Services/ProfileManagement/src/ProfileManagement.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: Services/Identity/src/IdentityService/Dockerfile
