version: '3.4'

services:
  sportdb:
    image: postgres

  matchingdb:
    image: postgres

  distributedcache:
    image: redis

  profiledb:
    image: mcr.microsoft.com/mssql/server

  sport.api:
    image: ${DOCKER_REGISTRY-}sportapi
    build:
      context: .
      dockerfile: Services/Sport/Sport.API/Dockerfile

  matching.api:
    image: ${DOCKER_REGISTRY-}matchingapi
    build:
      context: .
      dockerfile: Services/Matching/src/Matching.API/Dockerfile

volumes:
  postgres_sport:
  postgres_matching:


