version: '3.4'

services:
  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.templates.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
        
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mssqldb:
    container_name: mssqldb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    restart: always
    ports:
      - "1433:1433"

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  messagebroker:
    container_name: messagebroker
    hostname: sportybuddies-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  sport.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mssqldb;Database=SportDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - MessageBroker__Host=amqp://sportybuddies-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Jwt__Authority=http://identityservice:8080
      - Jwt__Audience=sport-api
      - Jwt__RequireHttpsMetadata=false
      - Jwt__MetadataAddress=http://identityservice:8080/.well-known/openid-configuration
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    restart: always
    depends_on:
      - mssqldb
      - messagebroker
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  matching.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mssqldb;Database=MatchesDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True;
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__BuddiesUrl=https://buddies.api:8081
      - GrpcSettings__ProfileUrl=https://profilemanagement.api:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - MessageBroker__Host=amqp://sportybuddies-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - IdentityServiceUrl=http://identityservice:8080
      - Jwt__Authority=http://identityservice:8080
      - Jwt__Audience=matching-api
      - Jwt__RequireHttpsMetadata=false
      - Jwt__MetadataAddress=http://identityservice:8080/.well-known/openid-configuration
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    restart: always
    depends_on:
      - mssqldb
      - distributedcache
      - messagebroker
      - buddies.api
      - profilemanagement.api
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  buddies.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mssqldb;Database=BuddiesDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True;
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - Jwt__Authority=http://identityservice:8080
      - Jwt__Audience=buddies-api
      - Jwt__RequireHttpsMetadata=false
      - Jwt__MetadataAddress=http://identityservice:8080/.well-known/openid-configuration
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    restart: always
    depends_on:
      - mssqldb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  profilemanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mssqldb;Database=ProfileDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True;
      - ConnectionStrings__Redis=distributedcache:6379
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - MessageBroker__Host=amqp://sportybuddies-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - FeatureManagement__Matching=false
      - IdentityServiceUrl=http://identityservice:8080
      - Jwt__Authority=http://identityservice:8080
      - Jwt__Audience=profilemanagement-api
      - Jwt__RequireHttpsMetadata=false
      - Jwt__MetadataAddress=http://identityservice:8080/.well-known/openid-configuration
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - MongoOptions__ConnectionString=mongodb://admin:admin@mongodb:27017
    restart: always
    depends_on:
      - mssqldb
      - mongodb
      - messagebroker
      - distributedcache
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - IdentityServiceUrl=http://identityservice:8080
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    restart: always
    depends_on:
      - sport.api
      - matching.api
      - profilemanagement.api
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=mssqldb;Database=IdentityDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True;
      - MessageBroker__Host=amqp://sportybuddies-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - AuthOptions__IssuerUri=http://identityservice:8080
      - ElasticConfiguration__Uri=http://elasticsearch:9200
    restart: always
    depends_on:
      - mssqldb
      - messagebroker
    ports:
      - "6065:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./keys:/app/keys