version: '3.4'

services:
  sportdb:
    image: postgres

  matchingdb:
    image: postgres

  distributedcache:
    image: redis

  profiledb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  sport.api:
    image: ${DOCKER_REGISTRY-}sportapi
    build:
      context: .
      dockerfile: Services/Sport/Sport.API/Dockerfile

  matching.api:
    image: ${DOCKER_REGISTRY-}matchingapi
    build:
      context: .
      dockerfile: Services/Matching/src/Matching.API/Dockerfile

  buddies.grpc:
    image: ${DOCKER_REGISTRY-}buddiesgrpc
    build:
      context: .
      dockerfile: Services/Buddies/src/Buddies.Grpc/Dockerfile

  profilemanagement.api:
    image: ${DOCKER_REGISTRY-}profilemanagementapi
    build:
      context: .
      dockerfile: Services/ProfileManagement/src/ProfileManagement.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_sport:
  postgres_matching:
